### ISSUE TITLE
Example for prompt=none

### ISSUE THREAD

**Issue by nynymike** [rohe/pyoidc#108]
I'd like to write a program that uses the pyoidc from a native application to validate credentials using prompt=none. Is there an example or test case for this that I could look at?

**Comment by rohe** [comment]
> 2 aug 2015 kl. 04:41 skrev Mike Schwartz <notifications@github.com>:
> 
> I'd like to write a program that uses the pyoidc from a native application to validate credentials using prompt=none. Is there an example or test case for this that I could look at?

There are test cases, for instance:

test_server_authorization_endpoint_request() and
test_server_authorization_endpoint_id_token()

both in test_oic_provider.py

- Roland

”Capitalism is the extraordinary belief that the nastiest of men for the nastiest of motives will somehow work for the benefit of all" - John Maynard Keynes.
