### ISSUE TITLE
Registration expiration

### ISSUE THREAD

**Issue by tpazderka** [rohe/pyoidc#112]
When a new registration is returned from the `registration_endpoint`, it contains a non-zero value in `client_secret_expires_at`. This indicates that after this time, the secret should not be valid but it is not true. The validity of secret is not checked anywhere during the processing of the requests.
According to specifications, this should return `0` in `client_secret_expires_at`.

But I think it would be more useful to add the checking of the `client_secret` validity to the code as well as a configuration option for the validity itself.

**Comment by rohe** [comment]
I've added a function for validating a client registration which basically is checking if the client_secret_expired_at time has passed or not.

**Comment by tpazderka** [comment]
Resolved, thanks!
