### ISSUE TITLE
newstr URI returned by oaut2 client uri_and_body on Python 2

### ISSUE THREAD

**Issue by flibbertigibbet** [rohe/pyoidc#161]
Redirect to provider to authenticate when using [django-oidc](https://github.com/marcanpilami/django-oidc) fails with TypeError:

```
'in <string>' requires string as left operand, not int
```

on attempting to parse the URI, which is a `newstr` when using Python 2.

**Comment by lwm** [comment]
Hi @flibbertigibbet, I'm not really sure what happened with this one, seeing as you closed the PR you submitted. Just triaging issues and will close this one off. Do re-open if there is something you still want to resolve.
