### ISSUE TITLE
can't parse response

### ISSUE THREAD

**Issue by mateusdemboski** [rohe/pyoidc#175]
Hi, A trying parse the response after authenticate with server, but the mthod return "NoSuitableSigningKeys: No key with kid: ckMcBA9k6q3J-ZAlHPhfWuH4Uuw"

Here is my code: https://gist.github.com/mateusdemboski/e1a8f6c600d3832d2dea

Anybody can help me?

**Comment by rohe** [comment]
> 8 mar 2016 kl. 21:22 skrev Mateus Demboski <notifications@github.com>:
> 
> Hi, A trying parse the response after authenticate with server, but the mthod return "NoSuitableSigningKeys: No key with kid: ckMcBA9k6q3J-ZAlHPhfWuH4Uuw"
> 
> Here is my code: https://gist.github.com/mateusdemboski/e1a8f6c600d3832d2dea
> 
> Anybody can help me?

You’ve chosen the ’code id_token token’ response_type which means that you get back an ID Token in the
response from the OP. This token is by default signed by the OP.

If you don’t have the OPs keys (and I see nothing in your code that shows me that you do) then you
can not verify the signature for the obvious reason.

It looks like you’re doing static client registration and also at least to some extend static provider configuration discovery.
So maybe the OP doesn’t support dynamic key fetching if so you have to do it in some out of bad way.

— Roland

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by rohe** [comment]
s/bad/band/ :-)

> 9 mar 2016 kl. 09:19 skrev Roland Hedberg <roland.hedberg@adm.umu.se>:
> 
> 
>> 8 mar 2016 kl. 21:22 skrev Mateus Demboski <notifications@github.com>:
>> 
>> Hi, A trying parse the response after authenticate with server, but the mthod return "NoSuitableSigningKeys: No key with kid: ckMcBA9k6q3J-ZAlHPhfWuH4Uuw"
>> 
>> Here is my code: https://gist.github.com/mateusdemboski/e1a8f6c600d3832d2dea
>> 
>> Anybody can help me?
> 
> You’ve chosen the ’code id_token token’ response_type which means that you get back an ID Token in the
> response from the OP. This token is by default signed by the OP.
> 
> If you don’t have the OPs keys (and I see nothing in your code that shows me that you do) then you
> can not verify the signature for the obvious reason.
> 
> It looks like you’re doing static client registration and also at least to some extend static provider configuration discovery.
> So maybe the OP doesn’t support dynamic key fetching if so you have to do it in some out of bad way.
> 
> — Roland
> 
> ”Everybody should be quiet near a little stream and listen."
> From ’Open House for Butterflies’ by Ruth Krauss
> 

— Roland

”Everybody should be quiet near a little stream and listen."
From ’Open House for Butterflies’ by Ruth Krauss

**Comment by mateusdemboski** [comment]
I hadn't setted the issuer in provider_config.
the problem has bean solved
