### ISSUE TITLE
CasAuthnMethod Login URI Incorrect

### ISSUE THREAD

**Issue by serac** [rohe/pyoidc#190]
Per the (CAS Protocol)[http://jasig.github.io/cas/development/protocol/CAS-Protocol-V2-Specification.html], the _/login_ URI is derived from the base URL. Presently the login URI is assumed to be "/cas/login", which is incorrect per the protocol. If a context path is needed, it should be provided via configuration parameter, e.g. "https://cas.example.com/cas", thereby producing "https://cas.example.com/cas/login."

**Comment by serac** [comment]
Pull #191 has candidate fix.

**Comment by lwm** [comment]
Since #191 is merged, closing this one off. Thanks @serac!
