### ISSUE TITLE
UserInfoLDAP Enhancements

### ISSUE THREAD

**Issue by serac** [rohe/pyoidc#192]
The `UserInfoLDAP` component could benefit from a couple enhancements:
1. Proper support for StartTLS.
2. Ability to configure the mapping of LDAP attribute names to OpenID Connect claims.

**Comment by serac** [comment]
Pull #193 has candidate fix.

**Comment by lwm** [comment]
@serac, since #193 is merged, this can then be closed off or?

**Comment by serac** [comment]
Free to close, thanks.
