### ISSUE TITLE
No docs?

### ISSUE THREAD

**Issue by nblott** [rohe/pyoidc#218]
I found these docs but not 100% certain this is the same project. Should add them to the wiki for clarity
http://pyoidc.readthedocs.io/en/latest/howto/index.html

**Comment by bearcattom** [comment]
bumping this thread...are these the official docs?

**Comment by rohe** [comment]
Yes, they are!

> 3 jan. 2017 kl. 16:35 skrev Tom Schultz <notifications@github.com>:
> 
> bumping this thread...are these the official docs?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain
