### ISSUE TITLE
Security: Logging captures credentials

### ISSUE THREAD

**Issue by bjmc** [rohe/pyoidc#228]
Some of the `debug` logging e.g. https://github.com/rohe/pyoidc/blob/master/src/oic/utils/authn/user.py#L306 captures raw cleartext passwords as entered by users. 

And even the `info` loglevel captures access tokens in the responses: https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L988

This is potentially dangerous, and I think it would be better to sanitize any credentials or secrets before logging.

**Comment by rohe** [comment]
> 7 okt. 2016 kl. 00:00 skrev Brendan McCollam <notifications@github.com>:
> 
> Some of the debug logging e.g. https://github.com/rohe/pyoidc/blob/master/src/oic/utils/authn/user.py#L306 <https://github.com/rohe/pyoidc/blob/master/src/oic/utils/authn/user.py#L306> captures raw cleartext passwords as entered by users.
> 
> And even the info loglevel captures access tokens in the responses: https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L988 <https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L988>
> This is potentially dangerous, and I think it would be better to sanitize any credentials or secrets before logging.
> 

Correct, attacks using information from log files has been describe.
I’ll put it on my list to do unless you want to do it ?

— Roland

**Comment by bjmc** [comment]
I can do it, but I won't have time until next week.

**Comment by rohe** [comment]
I’d appreciate if you would take this on.
Let me know if you’re unable for any reason and I’ll take over.

> 7 okt. 2016 kl. 08:57 skrev Brendan McCollam <notifications@github.com>:
> 
> I can do it, but I won't have time until next week.
> 
> On 7 October 2016 07:43:12 BST, Roland Hedberg <notifications@github.com> wrote:
> >
> >> 7 okt. 2016 kl. 00:00 skrev Brendan McCollam
> ><notifications@github.com>:
> >> 
> >> Some of the debug logging e.g.
> >https://github.com/rohe/pyoidc/blob/master/src/oic/utils/authn/user.py#L306
> ><https://github.com/rohe/pyoidc/blob/master/src/oic/utils/authn/user.py#L306>
> >captures raw cleartext passwords as entered by users.
> >> 
> >> And even the info loglevel captures access tokens in the responses:
> >https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L988
> ><https://github.com/rohe/pyoidc/blob/master/src/oic/oic/provider.py#L988>
> >> This is potentially dangerous, and I think it would be better to
> >sanitize any credentials or secrets before logging.
> >> 
> >
> >Correct, attacks using information from log files has been describe.
> >I’ll put it on my list to do unless you want to do it ?
> >
> >— Roland
> >
> >
> >
> >-- 
> >You are receiving this because you authored the thread.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/rohe/pyoidc/issues/228#issuecomment-252165243
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain
