### ISSUE TITLE
How to get uid?

### ISSUE THREAD

**Issue by konvalik** [rohe/pyoidc#239]
Hi,

is possible get uid of the user,that is authenticated? 

When i calling client.do_user_info_request() i get only "sub" - number, but i need uid - e.g. xxx@mojeid.cz

Thx for your help.
Petr

**Comment by rohe** [comment]
> 10 nov. 2016 kl. 16:01 skrev konvalik <notifications@github.com>:
> 
> Hi,
> 
> is possible get uid of the user,that is authenticated?
> 
> When i calling client.do_user_info_request() i get only ”sub" - number, but i need uid - e.g. xxx@mojeid.cz

Whether you get uid or not is completely in the hands of the OP.
Note that ’uid’ is not among the list of standard attributes.

http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain
