### ISSUE TITLE
server: Exception when calling end_session

### ISSUE THREAD

**Issue by pvalsecc** [rohe/pyoidc#246]
I'm using a customized version of oidc_example/op2 version 0.9.4.0. When calling the /end_session URL to logout the user (without any redirection parameter), I get this stacktrace on the server:
```
oauth_1    | 2017-01-03 15:56:55,079 ERROR oicServer WSGI response header key u'Set-Cookie' is not of type str.
oauth_1    | Traceback (most recent call last):
oauth_1    |   File "./server.py", line 380, in application
oauth_1    |     return callback(environ, start_response, logger)
oauth_1    |   File "./server.py", line 205, in endsession
oauth_1    |     logger=logger)
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/oic/utils/http_util.py", line 397, in wsgi_wrapper
oauth_1    |     return resp(environ, start_response)
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/oic/utils/http_util.py", line 49, in __call__
oauth_1    |     start_response(self.status, self.headers)
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2173, in start_response
oauth_1    |     raise TypeError("WSGI response header key %r is not of type str." % k)
oauth_1    | TypeError: WSGI response header key u'Set-Cookie' is not of type str.
oauth_1    | AssertionError('WSGI start_response called a second time with no exc_info.',)
oauth_1    | Traceback (most recent call last):
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
oauth_1    |     req.respond()
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
oauth_1    |     self.server.gateway(self).respond()
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2135, in respond
oauth_1    |     response = self.req.server.wsgi_app(self.env, self.start_response)
oauth_1    |   File "./server.py", line 387, in application
oauth_1    |     return resp(environ, start_response)
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/oic/utils/http_util.py", line 49, in __call__
oauth_1    |     start_response(self.status, self.headers)
oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2157, in start_response
oauth_1    |     raise AssertionError("WSGI start_response called a second "
oauth_1    | AssertionError: WSGI start_response called a second time with no exc_info.
```

I'm running it in a docker image based on python:2.7.

**Comment by rohe** [comment]
> 4 jan. 2017 kl. 07:49 skrev Patrick Valsecchi <notifications@github.com>:
> 
> I'm using a customized version of oidc_example/op2 version 0.9.4.0. When calling the /end_session URL to logout the user (without any redirection parameter), I get this stacktrace on the server:
> 
> oauth_1    | 2017-01-03 15:56:55,079 ERROR oicServer WSGI response header key u'Set-Cookie' is not of type str.
> oauth_1    | Traceback (most recent call last):
> oauth_1    |   File "./server.py", line 380, in application
> oauth_1    |     return callback(environ, start_response, logger)
> oauth_1    |   File "./server.py", line 205, in endsession
> oauth_1    |     logger=logger)
> oauth_1    |   File "/usr/local/lib/python2.7/site-packages/oic/utils/http_util.py", line 397, in wsgi_wrapper
> oauth_1    |     return resp(environ, start_response)
> oauth_1    |   File "/usr/local/lib/python2.7/site-packages/oic/utils/http_util.py", line 49, in __call__
> oauth_1    |     start_response(self.status, self.headers)
> oauth_1    |   File "/usr/local/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2173, in start_response
> oauth_1    |     raise TypeError("WSGI response header key %r is not of type str." % k)
> oauth_1    | TypeError: WSGI response header key u’Set-Cookie' is not of type str.

So the above line is the crucial one.

Looks to me like you have a Unicode problem.

I’m almost solely running 3.5 now so I may miss 2.7 specific problems.

Have a look at what happens on this line (~ line 594 in src/oic/oic/provider.py)

headers = [authn.delete_cookie(), self.delete_session_cookie()]

If this doesn’t produce strings then it might be your problem.
I haven’t time to look into this myself right now.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by pvalsecc** [comment]
Working like a champ on python 3.5. I don't remember why I've switched to 2.7 to run it. I guess it was not working back then (3.5 is my usual choice), but now, works even better than with 2.7.
Thanks.

**Comment by rohe** [comment]
> 7 jan. 2017 kl. 22:09 skrev Patrick Valsecchi <notifications@github.com>:
> 
> Working like a champ on python 3.5. I don't remember why I've switched to 2.7 to run it. I guess it was not working back then (3.5 is my usual choice), but now, works even better than with 2.7.

Sounds good to me !

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain
