### ISSUE TITLE
Examples: They're great, but they're broken? :|

### ISSUE THREAD

**Issue by lwm** [rohe/pyoidc#254]
I have been unable to get a working example of any OP/RP combination:
  * simple_op/rp seem to be only Python 2 compatible?
  * The docker setup results in a HTTP 500 (traceback [is here]).
  * op2/3 X rp2/3 examples resulted in a `WebFingerError` (traceback [is also here]).

Issues #212, #136, #56, #43 and #25 seem relevant.

Do you have any thoughts about reducing these examples to a *single working example*? If so, which example would that be? This would greatly reduce maintenance and help users.

My preference would be the Docker example, as I added in #255.

[is here]: https://gist.githubusercontent.com/lwm/f1d0271b41e598f91d4d7304c4b65e72/raw/6d60e2b19685ffb23a257c3ec36f37b5ebefd785/pyoidc-traceback.py
[is also here]: https://gist.githubusercontent.com/lwm/50575a036be253db4cf4a36ad1f5b281/raw/9782853b6d5f61ff99680dd04c9273b698e0ace9/pyodic-traceback2.py

**Comment by lwm** [comment]
Could we merge the docker stuff (from https://github.com/its-dirg/docker/) into this repository so that we could manage any problems that people have here?

**Comment by lwm** [comment]
So, after reviewing the Docker example, it all runs off the simple_op/rp examples. Could we merge the Docker code from `its-dirg/docker` here and just get the simple_op/rp examples working rock solid?

**Comment by rohe** [comment]
First, whenever I need an RP I use rp3, when I need an OP I use op2.
We should probably remove the others.
And yes, we should move the docker stuff from its-dirg.
its-dirg is not and will never be maintained  again.

**Comment by santosh0705** [comment]
I'm a beginner in OpenID Connect and pyoidc. None of the example worked for me. The provided document seems old and not synced with latest code. Is there any working example available to get started.

**Comment by lwm** [comment]
@santosh0705, please see https://github.com/OpenIDC/pyoidc#examples.

**Comment by santosh0705** [comment]
I tried with simple_op, simple_rp which didn't work. I may be missing something :( Its authenticating using username and password but not setting cookie and coming back to same authentication page.
Also tried op2, rp3 but it also didn't work.
