### ISSUE TITLE
AuthzHandling: Why __call__ only returns the empty string?

### ISSUE THREAD

**Issue by lwm** [rohe/pyoidc#258]
```
class AuthzHandling(CookieDealer):
    """ Class that allow an entity to manage authorization """

    def __call__(self, *args, **kwargs):
        return ""
```

Which is then called in `_complete_authz`:

```
        # Do the authorization
        try:
            permission = self.authz(user, client_id=areq['client_id'])
            self.sdb.update(sid, "permission", permission)
        except Exception:
            raise
```

Is this by design?

Regarding the docstring, I thought the `self.auth_broker` for the `Provider` was supposed to handle the authorization. Via your guide to implement an OP, one must inherit from `UserAuthnMethod` and implement various methods.

Confused as to what to do here. It's a mandatory argument to `Provider`.

Any help appreciated!

Thanks!

**Comment by rohe** [comment]
You have to distinguish between authentication and authorisation.
auth_broker handles authentication and AuthHandling does authorisation.

Before you can apply any authorisation rules you need to know who you are dealing with, so
authorisation as a whole consists of two parts: authentication + permission discovery/decision.

The first done by auth_broker and the second by self.authz.

**Comment by lwm** [comment]
Great, thanks for clarifying!!!
