### ISSUE TITLE
Compatibility with Python3?

### ISSUE THREAD

**Issue by yonyonson** [rohe/pyoidc#34]
Was trying to get use of pyoidc with Python 3.4 and ran into issues with jwt library that uses itertools.izip (not available in Python3 any more).
My questions are:
- Are there any plans to get pyoidc compatible with Python 3?
- Probably pic package at pypi site should be marked as uncompatible with Python 3 for now ([it has no compatibility info so far](https://pypi.python.org/pypi/oic/) )?

**Comment by DavidHwu** [comment]
Google Plus OpenID Connect will be in effect April 2015, 2 months away.
Any update on this?
Google is deprecating their OpenID support via Google.com and making OpenID Connect the defacto standard.

Oauth2 is also being deprecated in 2017.

Thanks!

**Comment by rohe** [comment]
> 19 feb 2015 kl. 23:49 skrev Bluevalor <notifications@github.com>:
> 
> Google Plus OpenID Connect will be in effect April 2015, 2 months away.
> Any update on this?

Yeah, I know this.
I also know that Google are working on a correct implementation of OpenID Connect.
The one they are presently using is not compliant with the standard.

Regarding python3 support, it will not happen before PyCon US :-/
But I hope to get time to do it beginning of May.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by lwm** [comment]
Oh, I'd like to help. Is there some ongoing work in a branch somewhere? 

If not, I can start to take a look at it from scratch.

**Comment by fdriesenaar** [comment]
Well, you may have a look here:
https://github.com/digital-me/openidcp

**Comment by lwm** [comment]
@fdriesenaar, I don't get it? That's a totally different project, written in Java? 

This issue is about bringing Python3 support to **this** project.

**Comment by lwm** [comment]
Oh, I see the `tox.ini` already has a `py34` environment configured. 

Soooo, it looks like this is already done! https://travis-ci.org/rohe/pyoidc

I installed from `pip` and got a compat error. @rohe, does `pyoidc` need a new release?

:+1: :beers:

**Comment by fdriesenaar** [comment]
@lwm: Sorry – I missed that.
