### ISSUE TITLE
oic.oauth2.do_authorization_request() discards ht_args

### ISSUE THREAD

**Issue by jdreed** [rohe/pyoidc#54]
[line 956](https://github.com/rohe/pyoidc/blob/master/src/oic/oauth2/__init__.py#L956) is a no-op:

```
if http_args is None:
    http_args = ht_args
else:
    http_args.update(http_args)
```
Does nothing with ht_args if http_args is already set.  Line 956 probably wants to be:
```
    http_args.update(ht_args)
```

**Comment by rohe** [comment]
Fixed
