### ISSUE TITLE
Request: requirements.txt

### ISSUE THREAD

**Issue by DavidHwu** [rohe/pyoidc#74]
Kindly consider supporting a requirements.txt workflow.
Thanks

**Comment by rohe** [comment]
Not sure I get what you mean by that.

> 19 feb 2015 kl. 23:53 skrev Bluevalor <notifications@github.com>:
> 
> requirements.txt workflow

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by DavidHwu** [comment]
All Python packages should have a requirements file.  It enables one to not guess what needs and versions are dependency you have for your package.

In this case I was wondering which component wasn't Python 3 and had to dig a but before finding it.

Here is a Python org reference

Thanks 

http://pip.readthedocs.org/en/1.1/requirements.html

**Comment by DavidHwu** [comment]
Love your Voltaire quote btw
So true
Going to borrow that for my emails :)

**Comment by rohe** [comment]
You’re welcome to it :-)

> 20 feb 2015 kl. 17:10 skrev Bluevalor <notifications@github.com>:
> 
> Love your Voltaire quote btw
> So true
> Going to borrow that for my emails :)
> 
> Sent from my iPhone
> 
> > On Feb 19, 2015, at 10:50 PM, Roland Hedberg <notifications@github.com> wrote:
> > 
> > "It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire
> —
> Reply to this email directly or view it on GitHub.
> 

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by avinash240** [comment]
@DavidHwu Why not just get this information from the setup.py file?  I'm fairly certain that's the language specific way to really do it.

**Comment by lwm** [comment]
@DavidHwu, there is now a `requirements.txt` in HEAD. This can be closed off?
