### ISSUE TITLE
sp_conf does not exist

### ISSUE THREAD

**Issue by herchila** [rohe/pyoidc#87]
Roland,

Sorry, but... where is the stripped down version of config.py that you normally use? ([previous issue](https://github.com/rohe/pyoidc/issues/50#issuecomment-64959257))

In op2 example I see two config files: config.py.simple and config.py.full and when I run `python server.py -p 8092 -d config`, return this: 

```
Traceback (most recent call last):
  File "server.py", line 478, in <module>
    userinfo=config.USERINFO)
  File "/home/herchila/Projects/virtualenv/pyoidc/local/lib/python2.7/site-packages/oic-0.7.6-py2.7.egg/oic/utils/authn/saml.py", line 75, in __init__
    self.sp_conf = importlib.import_module(spconf)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sp_conf
```

**Comment by rohe** [comment]
> 19 maj 2015 kl. 16:01 skrev Hernán Chilabert <notifications@github.com>:
> 
> Roland,
> 
> Sorry, but... where is the stripped down version of config.py that you normally use? (previous issue)
> 
> In op2 example I see two config files: config.py.simple andconfig.py.full and when I run python server.py -p 8092 -d config, return this:
> 
> ImportError: No module named sp_conf

This should only appear if you use config.py.full. That is copy config.py.full to config.py.
What you should do is: cp config.py.simple config.py
and then run the command: python server.py -p 8092 -d config

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by herchila** [comment]
That is what I did, I copied config.py.simple to config.py and then I ran the command but it didn't work... Also I did the same with config.py.full but it returned the same error...

Any clue?

**Comment by rohe** [comment]
> 19 maj 2015 kl. 19:14 skrev Hernán Chilabert <notifications@github.com>:
> 
> That is what I did, I copied config.py.simple to config.py and then I ran the command but it didn't work... Also I did the same with config.py.full but it returned the same error…

So, when you copied config.py.simple to config.py and ran the command what error message did you get ?

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by herchila** [comment]
Hi Roland,
In the first comment I explained what I did.

This is the error:

```
Traceback (most recent call last):
  File "server.py", line 478, in <module>
    userinfo=config.USERINFO)
  File "/home/herchila/Projects/virtualenv/pyoidc/local/lib/python2.7/site-packages/oic-0.7.6-py2.7.egg/oic/utils/authn/saml.py", line 75, in __init__
    self.sp_conf = importlib.import_module(spconf)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sp_conf
```

**Comment by herchila** [comment]
Hi!
Any clue?

**Comment by rohe** [comment]
> 26 maj 2015 kl. 22:25 skrev Hernán Chilabert <notifications@github.com>:
> 
> Hi!
> Any clue?

If you have SP_CONFIG defined in config.py remove it. If it’s not there I’d really like to see your config.py file.

If you’ve copied config.py.simple to config.py I don’t know how it got there since it it’s not
present in config.py.simple.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by herchila** [comment]
I am using config.py (replaced from config.py.simple) and SP_CONFIG is not defined...

And the other hand, when I run `python setup.py install`, the output is ok.
But, when I run the tests:

```
cd tests
py.test
```

the output is:

```
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.8 -- py-1.4.27 -- pytest-2.7.0
rootdir: /home/herchila/Projects/pyoidc, inifile: 
collected 2 items / 19 errors 

test_utils_for_tests.py ..

===================================================== ERRORS ======================================================
______________________________________ ERROR collecting tests/test_authn.py _______________________________________
test_authn.py:10: in <module>
    from oic.oic import JWT_BEARER
E   ImportError: No module named oic.oic
__________________________________ ERROR collecting tests/test_authn_context.py ___________________________________
test_authn_context.py:4: in <module>
    from oic.utils.authn.user import UsernamePasswordMako
E   ImportError: No module named oic.utils.authn.user
_____________________________________ ERROR collecting tests/test_clientdb.py _____________________________________
test_clientdb.py:3: in <module>
    import httpretty
E   ImportError: No module named httpretty
____________________________________ ERROR collecting tests/test_http_util.py _____________________________________
test_http_util.py:1: in <module>
    from oic.utils.http_util import CookieDealer
E   ImportError: No module named oic.utils.http_util
______________________________________ ERROR collecting tests/test_keyio.py _______________________________________
test_keyio.py:7: in <module>
    from oic.utils.keyio import key_export
E   ImportError: No module named oic.utils.keyio
______________________________________ ERROR collecting tests/test_oauth2.py ______________________________________
test_oauth2.py:11: in <module>
    from oic.oauth2 import Grant
E   ImportError: No module named oic.oauth2
_________________________________ ERROR collecting tests/test_oauth2_consumer.py __________________________________
test_oauth2_consumer.py:6: in <module>
    from oic.oauth2 import rndstr
E   ImportError: No module named oic.oauth2
__________________________________ ERROR collecting tests/test_oauth2_message.py __________________________________
test_oauth2_message.py:5: in <module>
    from oic.oauth2.message import *
E   ImportError: No module named oic.oauth2.message
_________________________________ ERROR collecting tests/test_oauth2_provider.py __________________________________
test_oauth2_provider.py:3: in <module>
    from oic.oauth2 import rndstr
E   ImportError: No module named oic.oauth2
_______________________________________ ERROR collecting tests/test_oic.py ________________________________________
test_oic.py:16: in <module>
    from oic.oic import Grant, DEF_SIGN_ALG
E   ImportError: No module named oic.oic
___________________________________ ERROR collecting tests/test_oic_consumer.py ___________________________________
test_oic_consumer.py:9: in <module>
    from oic.oauth2.message import MissingSigningKey
E   ImportError: No module named oic.oauth2.message
___________________________________ ERROR collecting tests/test_oic_message.py ____________________________________
test_oic_message.py:4: in <module>
    from oic.oauth2 import WrongSigningAlgorithm
E   ImportError: No module named oic.oauth2
___________________________________ ERROR collecting tests/test_oic_provider.py ___________________________________
test_oic_provider.py:11: in <module>
    from oic.oauth2 import rndstr
E   ImportError: No module named oic.oauth2
_______________________________________ ERROR collecting tests/test_sdb.py ________________________________________
test_sdb.py:1: in <module>
    from oic.utils.time_util import utc_time_sans_frac
E   ImportError: No module named oic.utils.time_util
____________________________________ ERROR collecting tests/test_stateless.py _____________________________________
test_stateless.py:1: in <module>
    from oic.utils.stateless import StateLess
E   ImportError: No module named oic.utils.stateless
____________________________________ ERROR collecting tests/test_time_util.py _____________________________________
test_time_util.py:6: in <module>
    from oic.utils.time_util import *
E   ImportError: No module named oic.utils.time_util
____________________________________ ERROR collecting tests/test_webfinger.py _____________________________________
test_webfinger.py:3: in <module>
    from oic.utils.webfinger import URINormalizer
E   ImportError: No module named oic.utils.webfinger
_____________________________________ ERROR collecting tests/test_x_claims.py _____________________________________
test_x_claims.py:4: in <module>
    from oic.utils.authn.authn_context import AuthnBroker
E   ImportError: No module named oic.utils.authn.authn_context
_____________________________________ ERROR collecting tests/test_x_dynreg.py _____________________________________
test_x_dynreg.py:2: in <module>
    from oic.utils.http_util import Response, NoContent, Unauthorized
E   ImportError: No module named oic.utils.http_util
======================================= 2 passed, 19 error in 0.21 seconds ========================================
```

**Comment by rohe** [comment]
You must have something seriously wrong with your installation.

> 28 maj 2015 kl. 20:58 skrev Hernán Chilabert <notifications@github.com>:
> 
> I am using config.py (replaced from config.py.simple) and SP_CONFIG is not defined...
> 
> And the other hand, when I run python setup.py install, the output is ok.

So sometimes (depending on OS) an older version of a packages is not removed when
a newer one is installed. So, how many pyoidc versions do you have ?

I don’t know about your setup but I find this on one of my production systems:

$ ls -ld /usr/local/lib/python2.7/dist-packages/oic*
drwxr-sr-x 5 root staff 4096 Mar 27 08:56 /usr/local/lib/python2.7/dist-packages/oic
drwxr-sr-x 2 root staff 4096 Mar 27 08:56 /usr/local/lib/python2.7/dist-packages/oic-0.7.5-py2.7.egg-info

If you have more then this remove all older versions by hand.

To check what your system wants to run you can do:

$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import oic
>>> help(oic)

The output here should tell you where the packages are installed and which one that is
preferred by your interpreter.

Hmm, should define VERSION.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by lwm** [comment]
@herchila, did you get this resolved? 

Closing for now, please feel free to re-open if you have more questions or something to resolve.
