### ISSUE TITLE
Google userinfo request failure

### ISSUE THREAD

**Issue by rdbhost** [rohe/pyoidc#98]
I am working with the rp3.py example, trying to get it working with a google email address; I uncommented the google portion of the conf.py, and edited in my client_id and secret.   The return_uri is set to /authz_cb, as the rp3.py file does not seem to have a '/google' path case in its  'application' function.

The login process completes the round-trip to and from google's server, but the login process fails at the do_user_info_request, with a 401 error and 'invalid_token' and 'Invalid Credentials' in the json body.

**Comment by rohe** [comment]
> 3 jun 2015 kl. 05:53 skrev David Keeney <notifications@github.com>:
> 
> I am working with the rp3.py example, trying to get it working with a google email address; I uncommented the google portion of the conf.py, and edited in my client_id and secret. The return_uri is set to /authz_cb, as the rp3.py file does not seem to have a ’/google' path case in its 'application' function.

Should make the code more intelligent on this topic.

> The login process completes the round-trip to and from google's server, but the login process fails at the do_user_info_request, with a 401 error and 'invalid_token' and 'Invalid Credentials' in the json body.

Yes, when getting userinfo the access token, according to the standard, can be sent in two ways: if GET in the HTTP header or as a POST body. POST is the default for pyoidc, Google prefers GET.

Made a slight change to the code and added a parameter to the configuration to make it work with Google.

Another change Google has applied is that the user information now is actually returned in the IdToken so getting the
information from the userinfo_endpoint is actually overkill :-/ but I’ll let it remain.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by rdbhost** [comment]
Wow. Fixed within 10 hours.

Awesome response!
